databases:
  - name: utility-app
    databaseName: utility_app_production
    user: menge

services:
  - type: web
    name: utility-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: utility-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false